package com.rockthecode.ledger.solution.tools

import com.rockthecode.ledger.solution._

import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, Path}
import scala.jdk.CollectionConverters._
import scala.util.Random

/**
 * Trainer tool: the seeded generator for the `huge` scenarios (1000+ lines).
 *
 *     sbt "runMain com.rockthecode.ledger.solution.tools.GenHuge src/main/resources/ledger"   (or: sbt ledgerGen)
 *
 * Every file has a fixed seed, so regenerating produces byte-identical output.
 * Each line is crafted against the reference's current state to hit a chosen
 * outcome, then run through the reference to record what it actually did. The
 * mix is roughly 55% accepted / 30% rejected (spread over every reason) / 10%
 * queries / 5% malformed, and the generator asserts that every rejection reason
 * and every ERROR variant of the milestone appears at least twice.
 *
 * Determinism rules: `Random(seed)` only; never iterate a Map or Set directly -
 * always through sorted keys.
 */
object GenHuge {

  /** What a milestone's vocabulary allows. Cumulative: 1 < 2 = 3 < 4 < 5. */
  final case class Level(n: Int) {
    val money      = n >= 2 // WITHDRAW FREEZE UNFREEZE CLOSE, all rejections, ERROR lines
    val transfers  = n >= 4
    val reports    = n >= 5 // HISTORY SUMMARY
    val rejections: List[String] =
      List("unknown-account", "account-exists") ++
        (if (money) List("unsupported-currency", "account-closed", "account-frozen", "non-positive-amount", "insufficient-funds", "non-zero-balance") else Nil) ++
        (if (transfers) List("same-account-transfer", "currency-mismatch") else Nil)
    val errors: List[String] =
      (if (money) List("unknown-command", "bad-arguments", "bad-account-id", "bad-amount", "bad-currency") else Nil) ++
        (if (reports) List("bad-sequence", "bad-range") else Nil)
  }

  final case class Job(file: String, level: Level, seed: Long, lines: Int, splitInto: Option[(String, String)] = None)

  val jobs: List[Job] = List(
    Job("m1/huge.in", Level(1), 1001L, 1000),
    Job("m2/huge.in", Level(2), 1002L, 1000),
    Job("m3/huge.in", Level(2), 1003L, 1000),
    Job("m4/huge.in", Level(4), 1004L, 1000),
    Job("m5/huge.in", Level(5), 1005L, 1000),
    Job("m3/replay-huge", Level(2), 1013L, 1000, Some(("m3/replay-huge-a.in", "m3/replay-huge-b.in"))),
    Job("m4/replay-huge", Level(4), 1014L, 1000, Some(("m4/replay-huge-a.in", "m4/replay-huge-b.in")))
  )

  def main(args: Array[String]): Unit = {
    val root = Path.of(args.head)
    jobs.foreach { job =>
      render(job, root).foreach { case (path, lines) =>
        val current = if (Files.exists(path)) Some(Files.readAllLines(path, UTF_8).asScala.toList) else None
        if (current.contains(lines)) println(s"  unchanged  $path")
        else { Files.write(path, lines.asJava, UTF_8); println(s"  written    $path (${lines.size} lines)") }
      }
    }
  }

  /** The exact files this job produces under `root`, without writing them. Used by `main` and by `Verify`. */
  private[tools] def render(job: Job, root: Path, quiet: Boolean = false): List[(Path, List[String])] = {
    val body = generate(job, quiet)
    job.splitInto match {
      case None => List((root.resolve(job.file), header(job, "") ++ body))
      case Some((a, b)) =>
        val (first, second) = body.splitAt(body.size / 2)
        List((root.resolve(a), header(job, " part A") ++ first), (root.resolve(b), header(job, " part B") ++ second))
    }
  }

  private def header(job: Job, part: String): List[String] = List(
    s"# purpose: machine-generated by GenHuge (seed ${job.seed}, milestone vocabulary m${job.level.n})$part. Do not edit; regenerate.",
    "# mix: ~55% accepted, ~30% rejected spread over every reason, ~10% queries, ~5% malformed; every rejection",
    "#      reason and ERROR variant of the milestone appears at least twice. Nobody is expected to read this file."
  )

  // ---------------------------------------------------------------------------

  private final case class State(bank: Bank, lines: Vector[String], coverage: Map[String, Int], nextId: Int, ghosts: Int)

  private def generate(job: Job, quiet: Boolean): List[String] = {
    val rnd = new Random(job.seed)
    val level = job.level
    val required = level.rejections ++ level.errors

    def loop(s: State): State =
      if (s.lines.size >= job.lines && required.forall(c => s.coverage.getOrElse(c, 0) >= 2)) s
      else if (s.lines.size >= job.lines * 2) sys.error(s"${job.file}: could not reach coverage; have ${s.coverage}")
      else loop(step(s, rnd, level))

    val done = loop(State(Bank.empty, Vector.empty, Map.empty, 1, 1))
    val table = required.map(c => f"    $c%-24s ${done.coverage.getOrElse(c, 0)}%4d").mkString("\n")
    val accepted = done.coverage.getOrElse("accepted", 0); val queries = done.coverage.getOrElse("query", 0)
    val rejected = level.rejections.map(done.coverage.getOrElse(_, 0)).sum; val errors = level.errors.map(done.coverage.getOrElse(_, 0)).sum
    if (!quiet) println(s"${job.file}: ${done.lines.size} lines - accepted $accepted, rejected $rejected, queries $queries, malformed $errors\n$table")
    required.find(c => done.coverage.getOrElse(c, 0) < 2).foreach(c => sys.error(s"coverage assertion failed for $c"))
    done.lines.toList
  }

  private def step(s: State, rnd: Random, level: Level): State = {
    val roll = rnd.nextInt(100)
    val (line, s1) =
      if (roll < (if (level.money) 55 else 65)) accept(s, rnd, level)
      else if (roll < (if (level.money) 85 else 90)) reject(s, rnd, level)
      else if (roll < 95 || !level.money) query(s, rnd, level)
      else malformed(s, rnd, level)
    val (bank, out) = ReferenceLedger.execute(s1.bank, line)
    val outcome = out.headOption match {
      case Some(o) if o.startsWith("OK ")       => "accepted"
      case Some(o) if o.startsWith("REJECTED ") => o.split(" ")(1)
      case Some(o) if o.startsWith("ERROR ")    => o.split(" ")(1)
      case Some(_)                              => "query"
      case None                                 => "comment"
    }
    s1.copy(bank = bank, lines = s1.lines :+ line, coverage = s1.coverage.updated(outcome, s1.coverage.getOrElse(outcome, 0) + 1))
  }

  // --- views of the bank, always in a deterministic order ----------------------

  private def sorted(b: Bank): List[Account] = b.accounts.keys.toList.sorted.map(b.accounts)
  private def actives(b: Bank): List[Account.Active] = sorted(b).collect { case a: Account.Active => a }
  private def open(b: Bank): List[Account.Active] = actives(b).filterNot(_.frozen)
  private def frozen(b: Bank): List[Account.Active] = actives(b).filter(_.frozen)
  private def closed(b: Bank): List[Account.Closed] = sorted(b).collect { case c: Account.Closed => c }
  private def live(b: Bank): List[Account.Active] = actives(b)
  private def funded(b: Bank): List[Account.Active] = open(b).filter(_.balance.isPositive)

  private def pick[A](xs: List[A], rnd: Random): A = xs(rnd.nextInt(xs.size))
  private val currencies = List("USD", "EUR", "GBP")

  private def amount(rnd: Random): String = {
    val cents = List(1, 5, 50, 100, 250, 999, 1000, 2500, 7777, 10000, 12345, 50000)(rnd.nextInt(12)) + rnd.nextInt(300)
    render(cents, rnd)
  }
  private def render(cents: Long, rnd: Random): String = {
    val two = Wire.money(Money(cents))
    if (two.endsWith(".00") && rnd.nextBoolean()) two.dropRight(3) else if (two.endsWith("0") && rnd.nextInt(3) == 0) two.dropRight(1) else two
  }

  // --- crafting -----------------------------------------------------------------

  private def newId(s: State): (String, State) = (f"acc-${s.nextId}%02d", s.copy(nextId = s.nextId + 1))

  private def accept(s: State, rnd: Random, level: Level): (String, State) = {
    val b = s.bank
    val opens = open(b)
    if (live(b).size < 6 || (live(b).size < 12 && rnd.nextInt(10) == 0)) {
      val (id, s1) = newId(s); (s"OPEN $id ${pick(currencies, rnd)}", s1)
    } else {
      val options = List.newBuilder[() => String]
      if (opens.nonEmpty) options += (() => s"DEPOSIT ${pick(opens, rnd).id} ${amount(rnd)}")
      if (opens.nonEmpty) options += (() => s"DEPOSIT ${pick(opens, rnd).id} ${amount(rnd)}")
      if (level.money && funded(b).nonEmpty) options += (() => { val a = pick(funded(b), rnd); s"WITHDRAW ${a.id} ${render(1 + rnd.nextLong(a.balance.cents), rnd)}" })
      if (level.money && funded(b).nonEmpty) options += (() => { val a = pick(funded(b), rnd); s"WITHDRAW ${a.id} ${render(1 + rnd.nextLong(a.balance.cents), rnd)}" })
      if (level.money && opens.size > 3 && frozen(b).size < 3) options += (() => s"FREEZE ${pick(opens, rnd).id}")
      if (level.money && frozen(b).nonEmpty) options += (() => s"UNFREEZE ${pick(frozen(b), rnd).id}")
      if (level.money && opens.size > 5 && closed(b).size < 4 && opens.exists(_.balance.isZero))
        options += (() => s"CLOSE ${pick(opens.filter(_.balance.isZero), rnd).id}")
      if (level.transfers) transferPair(b, rnd).foreach { case (from, to) =>
        options += (() => s"TRANSFER ${from.id} ${to.id} ${render(1 + rnd.nextLong(from.balance.cents), rnd)}")
        options += (() => s"TRANSFER ${from.id} ${to.id} ${render(1 + rnd.nextLong(from.balance.cents), rnd)}")
      }
      (pick(options.result(), rnd)(), s)
    }
  }

  /** A funded open source and an open same-currency destination, if any. */
  private def transferPair(b: Bank, rnd: Random): Option[(Account.Active, Account.Active)] = {
    val candidates = for {
      from <- funded(b)
      to <- open(b) if to.id != from.id && to.currency == from.currency
    } yield (from, to)
    if (candidates.isEmpty) None else Some(pick(candidates, rnd))
  }

  private def reject(s: State, rnd: Random, level: Level): (String, State) = {
    val b = s.bank
    val least = level.rejections.map(c => (c, s.coverage.getOrElse(c, 0))).sortBy(_._2)
    val code = pick(least.takeWhile(_._2 == least.head._2).map(_._1), rnd)
    val singleVerbs = List("DEPOSIT %s 5", "BALANCE %s") ++
      (if (level.money) List("WITHDRAW %s 5", "FREEZE %s", "UNFREEZE %s", "CLOSE %s") else Nil) ++
      (if (level.reports) List("HISTORY %s", "SUMMARY %s 1 5") else Nil)
    code match {
      case "unknown-account" =>
        val ghost = s"ghost-${s.ghosts}"
        val line = if (level.transfers && rnd.nextBoolean() && live(b).nonEmpty)
          (if (rnd.nextBoolean()) s"TRANSFER $ghost ${pick(live(b), rnd).id} 5" else s"TRANSFER ${pick(live(b), rnd).id} $ghost 5")
        else pick(singleVerbs, rnd).format(ghost)
        (line, s.copy(ghosts = s.ghosts + 1))
      case "account-exists" if sorted(b).nonEmpty => (s"OPEN ${pick(sorted(b), rnd).id} ${pick(currencies, rnd)}", s)
      case "unsupported-currency" => val (id, s1) = newId(s); (s"OPEN $id ${pick(List("JPY", "CHF", "XXX", "BTC"), rnd)}", s1)
      case "account-closed" =>
        closed(b) match {
          case Nil =>
            // prepare one: empty an open account, or close an already empty one
            open(b).find(_.balance.isZero) match {
              case Some(a) if open(b).size > 4 => (s"CLOSE ${a.id}", s)
              case _ if funded(b).nonEmpty => val a = pick(funded(b), rnd); (s"WITHDRAW ${a.id} ${Wire.money(a.balance)}", s)
              case _ => accept(s, rnd, level)
            }
          case cs =>
            val c = pick(cs, rnd)
            val line = if (level.transfers && rnd.nextBoolean() && open(b).nonEmpty)
              (if (rnd.nextBoolean()) s"TRANSFER ${c.id} ${pick(open(b), rnd).id} 5" else s"TRANSFER ${pick(open(b), rnd).id} ${c.id} 5")
            else pick(singleVerbs, rnd).format(c.id)
            (line, s)
        }
      case "account-frozen" =>
        frozen(b) match {
          case Nil if open(b).nonEmpty => (s"FREEZE ${pick(open(b), rnd).id}", s)
          case Nil => accept(s, rnd, level)
          case fs =>
            val f = pick(fs, rnd)
            val line = if (level.transfers && rnd.nextBoolean() && open(b).nonEmpty)
              (if (rnd.nextBoolean()) s"TRANSFER ${f.id} ${pick(open(b), rnd).id} 5" else s"TRANSFER ${pick(open(b), rnd).id} ${f.id} 5")
            else if (rnd.nextBoolean()) s"DEPOSIT ${f.id} ${amount(rnd)}" else s"WITHDRAW ${f.id} ${amount(rnd)}"
            (line, s)
        }
      case "non-positive-amount" if open(b).nonEmpty =>
        val a = pick(open(b), rnd); val bad = pick(List("0", "0.00", "-1", "-0.01", "-250.50"), rnd)
        val line = if (level.transfers && rnd.nextBoolean() && open(b).size > 1) s"TRANSFER ${a.id} ${pick(open(b).filter(_.id != a.id), rnd).id} $bad"
          else if (rnd.nextBoolean()) s"DEPOSIT ${a.id} $bad" else s"WITHDRAW ${a.id} $bad"
        (line, s)
      case "insufficient-funds" if open(b).nonEmpty =>
        val a = pick(open(b), rnd); val over = render(a.balance.cents + 1 + rnd.nextInt(5000), rnd)
        val same = open(b).filter(o => o.id != a.id && o.currency == a.currency)
        val line = if (level.transfers && same.nonEmpty && rnd.nextBoolean()) s"TRANSFER ${a.id} ${pick(same, rnd).id} $over" else s"WITHDRAW ${a.id} $over"
        (line, s)
      case "non-zero-balance" =>
        live(b).filter(_.balance.isPositive) match {
          case Nil if open(b).nonEmpty => (s"DEPOSIT ${pick(open(b), rnd).id} ${amount(rnd)}", s)
          case Nil => accept(s, rnd, level)
          case as => (s"CLOSE ${pick(as, rnd).id}", s)
        }
      case "same-account-transfer" =>
        val id = if (sorted(b).nonEmpty && rnd.nextInt(4) > 0) pick(sorted(b), rnd).id else "ghost-x"
        (s"TRANSFER $id $id ${amount(rnd)}", s)
      case "currency-mismatch" =>
        val pairs = for { f <- open(b); t <- open(b) if t.id != f.id && t.currency != f.currency } yield (f, t)
        if (pairs.isEmpty) accept(s, rnd, level) else { val (f, t) = pick(pairs, rnd); (s"TRANSFER ${f.id} ${t.id} ${amount(rnd)}", s) }
      case _ => accept(s, rnd, level)
    }
  }

  private def query(s: State, rnd: Random, level: Level): (String, State) = {
    val b = s.bank
    if (live(b).isEmpty) accept(s, rnd, level)
    else {
      val a = pick(live(b), rnd)
      val kinds = List(0, 0) ++ (if (level.reports) List(1, 2, 2) else Nil)
      pick(kinds, rnd) match {
        case 0 => (s"BALANCE ${a.id}", s)
        case 1 => (s"HISTORY ${a.id}", s)
        case _ =>
          val hi = b.nextSeq + 3
          val from = 1 + rnd.nextInt(hi); val to = from + rnd.nextInt(math.max(1, hi - from + 1))
          (s"SUMMARY ${a.id} $from $to", s)
      }
    }
  }

  private def malformed(s: State, rnd: Random, level: Level): (String, State) = {
    val b = s.bank
    val id = if (live(b).nonEmpty) pick(live(b), rnd).id else "acc-99"
    val least = level.errors.map(c => (c, s.coverage.getOrElse(c, 0))).sortBy(_._2)
    val code = pick(least.takeWhile(_._2 == least.head._2).map(_._1), rnd)
    val line = code match {
      case "unknown-command" => pick(List(s"deposit $id 5", s"balance $id", s"Withdraw $id 1", s"XFER $id acc-01 1", s"OPENED $id USD", "HELP"), rnd)
      case "bad-arguments"   => pick(List(s"DEPOSIT $id", "OPEN acc-50", "BALANCE", s"WITHDRAW $id 1 2", "FREEZE", s"CLOSE $id now", "TRANSFER acc-01 acc-02") ++ (if (level.reports) List(s"SUMMARY $id 1", "HISTORY") else Nil), rnd)
      case "bad-account-id"  => pick(List(s"DEPOSIT ${id.toUpperCase} 5", s"BALANCE ${id}_x", "OPEN Acc-9 USD", s"WITHDRAW ${id}! 1", "DEPOSIT a2345678901234567890123456789012x 1"), rnd)
      case "bad-amount"      => pick(List(s"DEPOSIT $id 1.005", s"WITHDRAW $id 5,50", s"DEPOSIT $id ten", s"WITHDRAW $id .5", s"DEPOSIT $id 5."), rnd)
      case "bad-currency"    => pick(List("OPEN acc-77 usd", "OPEN acc-77 EURO", "OPEN acc-77 US", "OPEN acc-77 $"), rnd)
      case "bad-sequence"    => pick(List(s"SUMMARY $id x 5", s"SUMMARY $id 1 -3", s"SUMMARY $id 1.5 2", s"SUMMARY $id one two"), rnd)
      case _                 => val to = 1 + rnd.nextInt(20); s"SUMMARY $id ${to + 1 + rnd.nextInt(10)} $to"
    }
    (line, s)
  }
}
